### ISSUE TITLE
Exception 

### ISSUE THREAD

**Issue by jasmeet2dhiman** [wouterdebie/i2cssh#110]
`Traceback (most recent call last):
  File "/usr/local/Cellar/i2cssh/0.0.3/libexec/lib/python3.10/site-packages/iterm2/connection.py", line 416, in async_connect
    return await coro(self)
  File "/usr/local/Cellar/i2cssh/0.0.3/libexec/lib/python3.10/site-packages/iterm2/connection.py", line 224, in async_main
    result = await coro(connection)
  File "/usr/local/bin/i2cssh", line 251, in inner
    ssh_prefix = create_ssh_prefix(opts)
  File "/usr/local/bin/i2cssh", line 312, in create_ssh_prefix
    k, v = extra.split("=")
ValueError: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/usr/local/Cellar/i2cssh/0.0.3/libexec/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 945, in transfer_data
    message = await self.read_message()
  File "/usr/local/Cellar/i2cssh/0.0.3/libexec/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1015, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/usr/local/Cellar/i2cssh/0.0.3/libexec/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1090, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/usr/local/Cellar/i2cssh/0.0.3/libexec/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1145, in read_frame
    frame = await Frame.read(
  File "/usr/local/Cellar/i2cssh/0.0.3/libexec/lib/python3.10/site-packages/websockets/legacy/framing.py", line 70, in read
    data = await reader(2)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/streams.py", line 705, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Cellar/i2cssh/0.0.3/libexec/lib/python3.10/site-packages/iterm2/connection.py", line 178, in _async_dispatch_forever
    data = await self.websocket.recv()
  File "/usr/local/Cellar/i2cssh/0.0.3/libexec/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 553, in recv
    await self.ensure_open()
  File "/usr/local/Cellar/i2cssh/0.0.3/libexec/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 921, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received`

**Comment by wouterdebie** [comment]
Would you mind adding both your config and command line to this? There's no way to figure out what's going on with just a stack trace.

**Comment by wouterdebie** [comment]
Closing this since there's no additional information..
