### ISSUE TITLE
'create_window_with_profile' (RuntimeError)

### ISSUE THREAD

**Issue by Govinda-Fichtner** [wouterdebie/i2cssh#50]
After a fresh install of i2cssh I get the following error:

```
$ i2cssh -c picocluster
/Users/govindaf/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rb-scpt-1.0.1/lib/rb-scpt.rb:676:in `rescue in method_missing': Unknown property, element or command: 'create_window_with_profile' (RuntimeError)
    from /Users/govindaf/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rb-scpt-1.0.1/lib/rb-scpt.rb:646:in `method_missing'
    from /Users/govindaf/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/i2cssh-2.0.0/lib/i2cssh.rb:20:in `initialize'
    from /Users/govindaf/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/i2cssh-2.0.0/bin/i2cssh:298:in `new'
    from /Users/govindaf/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/i2cssh-2.0.0/bin/i2cssh:298:in `<top (required)>'
    from /Users/govindaf/.rbenv/versions/2.3.0/bin/i2cssh:22:in `load'
    from /Users/govindaf/.rbenv/versions/2.3.0/bin/i2cssh:22:in `<main>'
```

I have the following version of i2cssh:

```
$ gem list i2cssh

*** LOCAL GEMS ***

i2cssh (2.0.0)
```

Ruby version: 2.3.0 (2015-12-25 patchlevel 0) [x86_64-darwin15]
iTerm: 2.1.4

Any hints how to fix this?

**Comment by jbornemann** [comment]
Hey, had the same issue. After I installed the 1.16.0 gem (as stated on the README for iterm versions < 2.9) it went away.
