### ISSUE TITLE
Installed RVM, i2cssh won't run anymore. 

### ISSUE THREAD

**Issue by kaushalmall** [wouterdebie/i2cssh#55]
I see the error below. 

```/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /Applications/vault-cli-3.1.6 in PATH, mode 040777
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'i2cssh' (>= 0) among 49 total gem(s) (Gem::LoadError)
       	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
       	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
       	from /usr/local/bin/i2cssh:22:in `<main>'```

rvm list gives me the list below 

```
rvm list

rvm rubies

=* ruby-2.3.0 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
```

I am not sure what other information I can provide. Pretty new to Ruby and have no idea how to debug this.

**Comment by kaushalmall** [comment]
uninstalling and installing i2cssh again fixed the issue.
