### ISSUE TITLE
Problems with -d (--direction)

### ISSUE THREAD

**Issue by fpedroza** [wouterdebie/i2cssh#58]
i2cssh v.2.2.0
iterm2 v.3.0.10

I would like my sessions to stack vertically instead of next to each other. I assume this can be accomplished with the -d (--direction) option or the -R (--rows) option. I'm getting the following error in both cases.

```
i2cssh --direction=row rprqa-app1 rprqa-app2
/Library/Ruby/Gems/2.0.0/gems/rb-scpt-1.0.1/lib/rb-scpt.rb:542:in `_send_command': CommandError (Appscript::CommandError)
        OSERROR: -1719
        MESSAGE: Access for assistive devices is disabled.
        OFFENDING OBJECT: app("/System/Library/CoreServices/System Events.app").processes["iTerm2"].menu_bars[1]
        COMMAND: app("/System/Library/CoreServices/System Events.app").processes["iTerm2"].menu_bars[1].menu_bar_items["Window"].menus["Window"].menu_items["Select Split Pane"].menus["Select Split Pane"].menu_items["Select Pane Above"].click()
    from /Library/Ruby/Gems/2.0.0/gems/rb-scpt-1.0.1/lib/rb-scpt.rb:642:in `method_missing'
    from /Library/Ruby/Gems/2.0.0/gems/i2cssh-2.2.0/lib/i2cssh.rb:103:in `block (2 levels) in split_session'
    from /Library/Ruby/Gems/2.0.0/gems/i2cssh-2.2.0/lib/i2cssh.rb:102:in `upto'
    from /Library/Ruby/Gems/2.0.0/gems/i2cssh-2.2.0/lib/i2cssh.rb:102:in `block in split_session'
    from /Library/Ruby/Gems/2.0.0/gems/i2cssh-2.2.0/lib/i2cssh.rb:101:in `upto'
    from /Library/Ruby/Gems/2.0.0/gems/i2cssh-2.2.0/lib/i2cssh.rb:101:in `split_session'
    from /Library/Ruby/Gems/2.0.0/gems/i2cssh-2.2.0/lib/i2cssh.rb:26:in `initialize'
    from /Library/Ruby/Gems/2.0.0/gems/i2cssh-2.2.0/bin/i2cssh:298:in `new'
    from /Library/Ruby/Gems/2.0.0/gems/i2cssh-2.2.0/bin/i2cssh:298:in `<top (required)>'
    from /usr/bin/i2cssh:23:in `load'
    from /usr/bin/i2cssh:23:in `<main>'
```

**Comment by fpedroza** [comment]
Some progress... I was able to get the -R option to work once I enabled accessibly access (http://mizage.com/help/accessibility.html). However, I still can't get -d  to work. No errors displayed... it just doesn't work.

**Comment by donkeyx** [comment]
I am having this same issue ^^
