### ISSUE TITLE
SSH'ng to a cluster, Stack trace

### ISSUE THREAD

**Issue by nynhex** [wouterdebie/i2cssh#68]
I just installed i2cssh with Ruby 2.4.0 and I'm configuring my cluster in ~/.i2csshrc as follows:

````
version: 2
clusters:
  c13:
   hosts:
     - dse01-use1-c13
     - dse02-use1-c13
     - dse03-use1-c13
     - dse04-use1-c13
     - dse05-use1-c13
     - dse06-use1-c13
     - dse07-use1-c13
     - dse08-use1-c13
````
When I try to do `i2cssh -c deploy@c13` I get the following stack trace:

````
dioxin:~ nynhex$ i2cssh -c deploy@c13
/Users/nynhex/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rb-scpt-1.0.1/lib/_aem/codecs.rb:236: warning: constant ::Fixnum is deprecated
/Users/nynhex/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rb-scpt-1.0.1/lib/_aem/codecs.rb:236: warning: constant ::Bignum is deprecated
/Users/nynhex/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rb-scpt-1.0.1/lib/_aem/codecs.rb:236: warning: constant ::Fixnum is deprecated
/Users/nynhex/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rb-scpt-1.0.1/lib/_aem/codecs.rb:236: warning: constant ::Bignum is deprecated
/Users/nynhex/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rb-scpt-1.0.1/lib/rb-scpt.rb:177:in `block in pack': Unknown Keyword: :terminal (IndexError)
	from /Users/nynhex/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rb-scpt-1.0.1/lib/rb-scpt.rb:177:in `fetch'
	from /Users/nynhex/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rb-scpt-1.0.1/lib/rb-scpt.rb:177:in `pack'
	from /Users/nynhex/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rb-scpt-1.0.1/lib/_aem/send.rb:37:in `block in initialize'
	from /Users/nynhex/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rb-scpt-1.0.1/lib/_aem/send.rb:37:in `each'
	from /Users/nynhex/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rb-scpt-1.0.1/lib/_aem/send.rb:37:in `initialize'
	from /Users/nynhex/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rb-scpt-1.0.1/lib/aem.rb:218:in `new'
	from /Users/nynhex/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rb-scpt-1.0.1/lib/aem.rb:218:in `event'
	from /Users/nynhex/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rb-scpt-1.0.1/lib/rb-scpt.rb:506:in `_send_command'
	from /Users/nynhex/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rb-scpt-1.0.1/lib/rb-scpt.rb:642:in `method_missing'
	from /Users/nynhex/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/i2cssh-1.16.0/lib/i2cssh.rb:19:in `initialize'
	from /Users/nynhex/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/i2cssh-1.16.0/bin/i2cssh:298:in `new'
	from /Users/nynhex/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/i2cssh-1.16.0/bin/i2cssh:298:in `<top (required)>'
	from /Users/nynhex/.rbenv/versions/2.4.0/bin/i2cssh:22:in `load'
	from /Users/nynhex/.rbenv/versions/2.4.0/bin/i2cssh:22:in `<main>'
````

I'm sorry if this is not configured correctly or I'm doing something wrong, but would really like to be able to login to a cluster at once and am unsure as to what's going wrong.

**Comment by nynhex** [comment]
I was able to resolve this by making a duplicate of iTerm2 and renaming it to iTerm.app
