### ISSUE TITLE
iterm2 (Build 3.3.7) and i2cssh (2.2.0) not working on MacOS Catalina

### ISSUE THREAD

**Issue by akang1** [wouterdebie/i2cssh#92]
After I upgraded to MacOS Catalina, and switched to use zsh, i2cssh is no longer working for me.

I am using iterm2 (Build 3.3.7) and i2cssh (2.2.0).

I am using this command to open SSH into multiple servers:

`i2cssh -b -Xp=3993 -l user user@hostname1 user@hostname12`

Here is the error I am getting:

```
Traceback (most recent call last):
	6: from /Users/akang/.rbenv/versions/2.6.3/bin/i2cssh:23:in `<main>'
	5: from /Users/akang/.rbenv/versions/2.6.3/bin/i2cssh:23:in `load'
	4: from /Users/akang/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/i2cssh-2.2.0/bin/i2cssh:298:in `<top (required)>'
	3: from /Users/akang/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/i2cssh-2.2.0/bin/i2cssh:298:in `new'
	2: from /Users/akang/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/i2cssh-2.2.0/lib/i2cssh.rb:21:in `initialize'
	1: from /Users/akang/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rb-scpt-1.0.3/lib/rb-scpt.rb:642:in `method_missing'
/Users/akang/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rb-scpt-1.0.3/lib/rb-scpt.rb:542:in `_send_command': CommandError (Appscript::CommandError)
		OSERROR: 1
		MESSAGE: No profile exists named 'Default'
		COMMAND: app("/Applications/iTerm.app").create_window_with_profile("Default", {:command=>"/usr/bin/env bash -l"})
```

PS: Even after i switch back to bash, i get the same error

**Comment by akang1** [comment]
The issue was that I changed the name of the default profile to "Default (Alien")... it looks like i2cssh only works when there is a default profile name "Default"
